# -*- coding: utf-8 -*-
"""Plant Disease Detection  Using Pretrained Model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/157GKwXOPGkGSmGObIs3O6PZlLv0EJYkS
"""

import tensorflow as tf
import matplotlib.pyplot as plt
import os
import numpy as np

from tensorflow.keras import layers, models
from tensorflow.keras.applications import MobileNetV2
from tensorflow.keras.applications.mobilenet_v2 import preprocess_input

import kagglehub

# Download latest version
path = kagglehub.dataset_download("mohitsingh1804/plantvillage")

print("Path to dataset files:", path)

path

PATH = os.path.join(os.path.dirname('C:\\Users\\rushi\\.cache\\kagglehub\\datasets\\mohitsingh1804\\plantvillage\\versions\\1\\PlantVillage\\'))

PATH

os.listdir(PATH)

train_dir = os.path.join(PATH, 'train')

train_dir

validation_dir = os.path.join(PATH, 'val')

validation_dir

BATCH_SIZE = 32
IMAGE_SIZE = (160,160)

train_ds = tf.keras.utils.image_dataset_from_directory(train_dir,
                                                      shuffle=True,
                                                      image_size=IMAGE_SIZE,
                                                      batch_size=BATCH_SIZE)

train_ds.class_names

validation_ds = tf.keras.utils.image_dataset_from_directory(validation_dir,
                                                           shuffle=True,
                                                           batch_size=BATCH_SIZE,
                                                           image_size=IMAGE_SIZE)

validation_ds.class_names

train_ds.take(1)

for img, lb in train_ds.take(1):
    print(img.shape)
    print(lb.shape)

for img, lb in train_ds.take(1):
    print(img)
    print(lb)

for img, lb in train_ds.take(1):
    print(img[0].numpy().astype('uint8'))
    print(lb[0].numpy())

class_names = train_ds.class_names

class_names

plt.figure(figsize=(10,10))
for images, labels in train_ds.take(1):
    for i in range(9):
        ax = plt.subplot(3,3,i+1)
        plt.imshow(images[i].numpy().astype('uint8'))
        plt.title(class_names[labels[i]])
        plt.axis('off')

val_batches = tf.data.experimental.cardinality(validation_ds)

val_batches

train_batches = tf.data.experimental.cardinality(train_ds)

train_batches

test_ds = validation_ds.take(val_batches // 5)
validation_ds = validation_ds.skip(val_batches // 5)

print('Number of test batches: %d' % tf.data.experimental.cardinality(test_ds))
print('Number of validation batches: %d' % tf.data.experimental.cardinality(validation_ds))

AUTOTUNE = tf.data.AUTOTUNE
train_dataset = train_ds.prefetch(buffer_size=AUTOTUNE)
validation_dataset = validation_ds.prefetch(buffer_size=AUTOTUNE)
test_dataset = test_ds.prefetch(buffer_size=AUTOTUNE)

data_augmentaion = tf.keras.Sequential([
    tf.keras.layers.RandomFlip('horizontal', input_shape=(160,160,3)),
    tf.keras.layers.RandomRotation(0.2)

])

plt.figure(figsize=(10,10))
for image, _ in train_dataset.take(1):
    first_image =image[0]
    for i in range(9):
        ax = plt.subplot(3,3,i+1)
        augmented_image = data_augmentaion(tf.expand_dims(first_image, 0))
        plt.imshow(augmented_image[0] / 255.0)
        plt.axis('off')

image_batch, label_batch = next(iter(train_dataset))
print(image_batch.shape)
print(label_batch.shape)

image_batch[0]

type(image_batch[0])

image_batch[0].numpy().astype('uint8')

plt.imshow(image_batch[0].numpy().astype('uint8'))
plt.show()

label_batch[0]

class_names[label_batch[0]]

base_model = MobileNetV2(
    input_shape=(160,160,3),
    include_top=False,
    weights='imagenet')

base_model.summary()

base_model.trainable = False

inputs = tf.keras.Input(shape=(160,160,3))
x = data_augmentaion(inputs)
x = preprocess_input(x)
x = base_model(x, training=False)
x = layers.GlobalAveragePooling2D()(x)
x = layers.Dropout(0.3)(x)
x = layers.Dense(128, activation='relu')(x)
outputs = layers.Dense(38, activation='softmax')(x)
model = tf.keras.Model(inputs, outputs)

model.summary()

base_learning_rate = 0.0001

model.compile(
    optimizer=tf.keras.optimizers.Adam(learning_rate=base_learning_rate),
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy'])

history = model.fit(train_dataset,
                   epochs=100,
                   validation_data=validation_dataset)

model.evaluate(validation_dataset)

acc = history.history['accuracy']
val_acc = history.history['val_accuracy']

loss = history.history['loss']
val_loss = history.history['val_loss']

plt.figure(figsize=(4, 8))
plt.subplot(2, 1, 1)
plt.plot(acc, label='Training Accuracy')
plt.plot(val_acc, label='Validation Accuracy')
plt.legend(loc='lower right')
plt.ylabel('Accuracy')
plt.ylim([min(plt.ylim()),1])
plt.title('Training and Validation Accuracy')

plt.subplot(2, 1, 2)
plt.plot(loss, label='Training Loss')
plt.plot(val_loss, label='Validation Loss')
plt.legend(loc='upper right')
plt.ylabel('Cross Entropy')
plt.ylim([0,1.0])
plt.title('Training and Validation Loss')
plt.xlabel('epoch')
plt.show()

from tensorflow.keras.utils import load_img,img_to_array

img = load_img('Apple___Black_rot.jpg',target_size=(160,160))

img

img_arr = img_to_array(img)

img_arr.shape

img_arr = img_arr.reshape(1,160,160,3)

img_arr.shape

model.predict(img_arr)

model.predict(img_arr)[0][0].round()

np.argmax(model.predict(img_arr)[0][0].round())

class_names[np.argmax(model.predict(img_arr)[0][0].round())]



